name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Selenium test
      run: npm test

    - name: Versioning
      uses: actions/setup-node@v2
      with:
        node-version: '14'
     
    
      run: |
        npm version patch
        git push --follow-tags

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build Docker image
      run: docker build -t schmelzii/webshop:latest .
      
      
    - name: Push Docker image
      run: docker push schmelzii/webshop:latest
